name: Create new release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: "v0.0.1"
        required: true
        description: "New release version"
      description:
        default: "Implements CI/CD pipeline"
        required: true
        description: "New release description"
        
jobs:
  new_release:
    runs-on: ubuntu-latest 
    outputs:
      release_id: "${{ steps.new_release.outputs.id }}"
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        id: new_release
        with:
          token: "${{ secrets.DUAL_WORKFLOWS }}"
          tag: "${{ github.event.inputs.tag }}"
          description: "${{ github.event.inputs.description }}"
          
  build_release:
    name: Build release
    needs: new_release
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            bin: dual-server-windows
            path: "target\\release\\dual-server-windows.exe"
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: "cargo build --release --bin ${{ matrix.bin }}"
      - name: List files
        run: "dir"
      - name: List files
        run: "dir target"
      - name: List files
        run: "dir target\\release"
      - uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: "${{ secrets.DUAL_WORKFLOWS }}"
        with:
          file: "${{ matrix.path }}"
          release_id: "${{ needs.new_release.outputs.release_id }}"
          verbose: true
