name: Create new release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: "v0.0.1"
        required: true
        description: "New release version"
      description:
        default: "Implements CI/CD pipeline"
        required: true
        description: "New release description"
        
jobs:
  new_release:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.DUAL_WORKFLOWS }}
          tag: "${{ github.event.inputs.tag }}"
          description: "${{ github.event.inputs.description }}"
          
  build_release:
    name: Build release
    needs: new_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            bin: dual-server-linux
          - os: macos-latest
            bin: dual-server-macos
          - os: windows-latest
            bin: dual-server-windows
    steps:
      - name: Build
        run: "cargo build --release --bin ${{ matrix.bin }}"
      - uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.DUAL_WORKFLOWS }}
        with:
          file: "target/release/${{ matrix.bin }}"
          update_latest_release: true
          verbose: true
